/**
 * AI Config File Generator
 *
 * Generates tool-specific AI context files during `spec-gen analyze`:
 *   - .cursorrules      (Cursor IDE)
 *   - .clinerules/spec-gen.md  (Cline / Roo Code / Kilocode)
 *   - CLAUDE.md         (Claude Code — only if not already present)
 *
 * Files are NEVER overwritten — if a file already exists it is skipped silently.
 * Returns the list of paths that were actually created.
 */

import { writeFile, mkdir, access } from 'node:fs/promises';
import { join, dirname } from 'node:path';

// ============================================================================
// TYPES
// ============================================================================

export interface AiConfigOptions {
  /** Absolute path to the project root */
  rootDir: string;
  /** Relative path to the analysis output directory (e.g. ".spec-gen/analysis") */
  analysisDir: string;
  /** Project name shown in the generated header */
  projectName: string;
}

// ============================================================================
// TEMPLATE
// ============================================================================

const MCP_TOOLS_TABLE = `
## spec-gen MCP tools — when to use them

| Situation | Tool |
|-----------|------|
| Starting any new task | \`orient\` — returns functions, files, specs, call paths, and insertion points in one call |
| Don't know which file/function handles a concept | \`search_code\` |
| Need call topology across many files | \`get_subgraph\` / \`analyze_impact\` |
| Planning where to add a feature | \`suggest_insertion_points\` |
| Reading a spec before writing code | \`get_spec\` |
| Checking if code still matches spec | \`check_spec_drift\` |
| Finding spec requirements by meaning | \`search_specs\` |
| Listing all API routes | \`get_route_inventory\` |
`.trim();

function buildContent(analysisDir: string, projectName: string, forClaude: boolean): string {
  const digestRef = forClaude
    ? `@${analysisDir}/CODEBASE.md`
    : `<!-- Import or paste ${analysisDir}/CODEBASE.md here for full project context -->`;

  return [
    `# ${projectName} — AI context (generated by spec-gen)`,
    '',
    digestRef,
    '',
    MCP_TOOLS_TABLE,
  ].join('\n');
}

// ============================================================================
// HELPERS
// ============================================================================

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function writeIfAbsent(filePath: string, content: string): Promise<boolean> {
  if (await fileExists(filePath)) return false;
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content, 'utf-8');
  return true;
}

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Generate AI tool config files in the project root.
 * Skips any file that already exists.
 *
 * @returns Relative paths (from rootDir) of files that were created.
 */
export async function generateAiConfigs(options: AiConfigOptions): Promise<string[]> {
  const { rootDir, analysisDir, projectName } = options;
  const created: string[] = [];

  const targets: Array<{ rel: string; forClaude: boolean }> = [
    { rel: '.cursorrules',         forClaude: false },
    { rel: '.clinerules/spec-gen.md', forClaude: false },
    { rel: 'CLAUDE.md',            forClaude: true  },
  ];

  await Promise.all(
    targets.map(async ({ rel, forClaude }) => {
      const absPath = join(rootDir, rel);
      const content = buildContent(analysisDir, projectName, forClaude);
      const wrote = await writeIfAbsent(absPath, content);
      if (wrote) created.push(rel);
    })
  );

  return created;
}
